from qutebrowser.api import interceptor
# Autogenerated config.py
#
# NOTE: config.py is intended for advanced users who are comfortable
# with manually migrating the config file on qutebrowser upgrades. If
# you prefer, you can also configure qutebrowser using the
# :set/:bind/:config-* commands without having to write a config.py
# file.
#
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Change the argument to True to still load settings configured via autoconfig.yml
config.load_autoconfig(False)

# Which cookies to accept. With QtWebEngine, this setting also controls
# other features with tracking capabilities similar to those of cookies;
# including IndexedDB, DOM storage, filesystem API, service workers, and
# AppCache. Note that with QtWebKit, only `all` and `never` are
# supported as per-domain values. Setting `no-3rdparty` or `no-
# unknown-3rdparty` per-domain on QtWebKit will have the same effect as
# `all`. If this setting is used with URL patterns, the pattern gets
# applied to the origin/first party URL of the page making the request,
# not the request URL. With QtWebEngine 5.15.0+, paths will be stripped
# from URLs, so URL patterns using paths will not match. With
# QtWebEngine 5.15.2+, subdomains are additionally stripped as well, so
# you will typically need to set this setting for `example.com` when the
# cookie is set on `somesubdomain.example.com` for it to work properly.
# To debug issues with this setting, start qutebrowser with `--debug
# --logfilter network --debug-flag log-cookies` which will show all
# cookies being set.
# Type: String
# Valid values:
#   - all: Accept all cookies.
#   - no-3rdparty: Accept cookies from the same origin only. This is known to break some sites, such as GMail.
#   - no-unknown-3rdparty: Accept cookies from the same origin only, unless a cookie is already set for the domain. On QtWebEngine, this is the same as no-3rdparty.
#   - never: Don't accept cookies at all.
config.set('content.cookies.accept', 'all', 'chrome-devtools://*')

# Which cookies to accept. With QtWebEngine, this setting also controls
# other features with tracking capabilities similar to those of cookies;
# including IndexedDB, DOM storage, filesystem API, service workers, and
# AppCache. Note that with QtWebKit, only `all` and `never` are
# supported as per-domain values. Setting `no-3rdparty` or `no-
# unknown-3rdparty` per-domain on QtWebKit will have the same effect as
# `all`. If this setting is used with URL patterns, the pattern gets
# applied to the origin/first party URL of the page making the request,
# not the request URL. With QtWebEngine 5.15.0+, paths will be stripped
# from URLs, so URL patterns using paths will not match. With
# QtWebEngine 5.15.2+, subdomains are additionally stripped as well, so
# you will typically need to set this setting for `example.com` when the
# cookie is set on `somesubdomain.example.com` for it to work properly.
# To debug issues with this setting, start qutebrowser with `--debug
# --logfilter network --debug-flag log-cookies` which will show all
# cookies being set.
# Type: String
# Valid values:
#   - all: Accept all cookies.
#   - no-3rdparty: Accept cookies from the same origin only. This is known to break some sites, such as GMail.
#   - no-unknown-3rdparty: Accept cookies from the same origin only, unless a cookie is already set for the domain. On QtWebEngine, this is the same as no-3rdparty.
#   - never: Don't accept cookies at all.
config.set('content.cookies.accept', 'all', 'devtools://*')

# Value to send in the `Accept-Language` header. Note that the value
# read from JavaScript is always the global value.
# Type: String
config.set('content.headers.accept_language', '', 'https://matchmaker.krunker.io/*')

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{upstream_browser_version_short}`: The
# corresponding Safari/Chrome   version, but only with its major
# version. * `{qutebrowser_version}`: The currently running qutebrowser
# version.  The default value is equal to the default user agent of
# QtWebKit/QtWebEngine, but with the `QtWebEngine/...` part removed for
# increased compatibility.  Note that the value read from JavaScript is
# always the global value.
# Type: FormatString
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}; rv:149.0) Gecko/20100101 Firefox/149.0', 'https://accounts.google.com/*')

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{upstream_browser_version_short}`: The
# corresponding Safari/Chrome   version, but only with its major
# version. * `{qutebrowser_version}`: The currently running qutebrowser
# version.  The default value is equal to the default user agent of
# QtWebKit/QtWebEngine, but with the `QtWebEngine/...` part removed for
# increased compatibility.  Note that the value read from JavaScript is
# always the global value.
# Type: FormatString
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {qt_key}/{qt_version} {upstream_browser_key}/{upstream_browser_version_short} Safari/{webkit_version}', 'https://gitlab.gnome.org/*')

# Load images automatically in web pages.
# Type: Bool
config.set('content.images', True, 'chrome-devtools://*')

# Load images automatically in web pages.
# Type: Bool
config.set('content.images', True, 'devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome-devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Allow locally loaded documents to access remote URLs.
# Type: Bool
config.set('content.local_content_can_access_remote_urls', True, 'file:///home/bunnie/.local/share/qutebrowser/userscripts/*')

# Allow locally loaded documents to access other local URLs.
# Type: Bool
config.set('content.local_content_can_access_file_urls', False, 'file:///home/bunnie/.local/share/qutebrowser/userscripts/*')

c.url.searchengines = {
    "DEFAULT": "https://www.google.com/search?q={}",
}

c.url.start_pages = ["about:blank"]
c.url.default_page = "about:blank"
config.set("colors.webpage.darkmode.enabled", True)
c.content.blocking.method = "both"
c.content.blocking.enabled = True
c.zoom.default = 125
c.content.cache.maximum_pages = 2
c.content.cache.size = 52428800

# ================== Youtube Add Blocking ======================= {{{
def filter_yt(info: interceptor.Request):
    """Block the given request if necessary."""
    url = info.request_url
    if (
        url.host() == "www.youtube.com"
        and url.path() == "/get_video_info"
        and "&adformat=" in url.query()
    ):
        info.block()


interceptor.register(filter_yt)
# }}}

# ================================================================
# ================== "daily dose of rice" theme =================
# ================================================================
# Cream-on-black palette pulled from your rofi launcher / wallpaper.
# Swap FONT_FAMILY below if you're not using a nerd font.

BG        = "#0a0a0a"   # near-black background
BG_ALT    = "#141414"   # slightly lighter black for panels/tabs
FG        = "#c9c2b3"   # muted warm grey-cream (body text)
FG_DIM    = "#6e6a60"   # dimmed/inactive text
CREAM     = "#e8dfd0"   # the highlighted-row cream from your launcher
CREAM_DIM = "#a89f8c"   # cream but muted, for secondary accents
BLACK     = "#000000"
BORDER    = "#2a2620"   # subtle warm-grey border/divider

FONT_FAMILY = "JetBrainsMono Nerd Font"
FONT_SIZE   = "11pt"

# ---- Fonts --------------------------------------------------------------
c.fonts.default_family = FONT_FAMILY
c.fonts.default_size = FONT_SIZE
c.fonts.completion.entry = f"{FONT_SIZE} {FONT_FAMILY}"
c.fonts.completion.category = f"bold {FONT_SIZE} {FONT_FAMILY}"
c.fonts.debug_console = f"{FONT_SIZE} {FONT_FAMILY}"
c.fonts.downloads = f"{FONT_SIZE} {FONT_FAMILY}"
c.fonts.hints = f"bold {FONT_SIZE} {FONT_FAMILY}"
c.fonts.keyhint = f"{FONT_SIZE} {FONT_FAMILY}"
c.fonts.messages.error = f"{FONT_SIZE} {FONT_FAMILY}"
c.fonts.messages.info = f"{FONT_SIZE} {FONT_FAMILY}"
c.fonts.messages.warning = f"{FONT_SIZE} {FONT_FAMILY}"
c.fonts.prompts = f"{FONT_SIZE} {FONT_FAMILY}"
c.fonts.statusbar = f"{FONT_SIZE} {FONT_FAMILY}"
c.fonts.tabs.selected = f"{FONT_SIZE} {FONT_FAMILY}"
c.fonts.tabs.unselected = f"{FONT_SIZE} {FONT_FAMILY}"

# ---- Completion menu (the command/search dropdown, styled like rofi) ----
c.colors.completion.fg = FG
c.colors.completion.odd.bg = BG
c.colors.completion.even.bg = BG
c.colors.completion.category.fg = CREAM
c.colors.completion.category.bg = BG_ALT
c.colors.completion.category.border.top = BORDER
c.colors.completion.category.border.bottom = BORDER
c.colors.completion.item.selected.fg = BLACK
c.colors.completion.item.selected.bg = CREAM
c.colors.completion.item.selected.border.top = CREAM
c.colors.completion.item.selected.border.bottom = CREAM
c.colors.completion.item.selected.match.fg = BLACK
c.colors.completion.match.fg = CREAM
c.colors.completion.scrollbar.fg = FG_DIM
c.colors.completion.scrollbar.bg = BG

# ---- Command / prompt / message bars ----
c.colors.prompts.fg = FG
c.colors.prompts.bg = BG_ALT
c.colors.prompts.border = f"1px solid {BORDER}"
c.colors.prompts.selected.bg = CREAM
c.colors.prompts.selected.fg = BLACK

c.colors.messages.info.fg = FG
c.colors.messages.info.bg = BG
c.colors.messages.info.border = BORDER
c.colors.messages.warning.fg = BLACK
c.colors.messages.warning.bg = CREAM_DIM
c.colors.messages.warning.border = CREAM_DIM
c.colors.messages.error.fg = BG
c.colors.messages.error.bg = "#c96a5a"   # muted warm red, still fits the palette
c.colors.messages.error.border = "#c96a5a"

# ---- Statusbar ----
c.colors.statusbar.normal.fg = FG
c.colors.statusbar.normal.bg = BG
c.colors.statusbar.insert.fg = BLACK
c.colors.statusbar.insert.bg = CREAM
c.colors.statusbar.passthrough.fg = BLACK
c.colors.statusbar.passthrough.bg = CREAM_DIM
c.colors.statusbar.command.fg = FG
c.colors.statusbar.command.bg = BG
c.colors.statusbar.caret.fg = BLACK
c.colors.statusbar.caret.bg = CREAM
c.colors.statusbar.caret.selection.fg = BLACK
c.colors.statusbar.caret.selection.bg = CREAM_DIM
c.colors.statusbar.url.fg = FG
c.colors.statusbar.url.success.http.fg = FG
c.colors.statusbar.url.success.https.fg = CREAM
c.colors.statusbar.url.hover.fg = CREAM_DIM
c.colors.statusbar.url.warn.fg = "#c9a25a"
c.colors.statusbar.url.error.fg = "#c96a5a"
c.colors.statusbar.progress.bg = CREAM

# ---- Tabs ----
c.colors.tabs.bar.bg = BG
c.colors.tabs.odd.fg = FG_DIM
c.colors.tabs.odd.bg = BG_ALT
c.colors.tabs.even.fg = FG_DIM
c.colors.tabs.even.bg = BG_ALT
c.colors.tabs.selected.odd.fg = BLACK
c.colors.tabs.selected.odd.bg = CREAM
c.colors.tabs.selected.even.fg = BLACK
c.colors.tabs.selected.even.bg = CREAM
c.colors.tabs.pinned.odd.bg = "#20241f"
c.colors.tabs.pinned.even.bg = "#20241f"
c.colors.tabs.pinned.selected.odd.bg = CREAM_DIM
c.colors.tabs.pinned.selected.even.bg = CREAM_DIM
c.colors.tabs.indicator.start = CREAM_DIM
c.colors.tabs.indicator.stop = CREAM
c.colors.tabs.indicator.error = "#c96a5a"

# Minimal tab layout, matching the launcher's clean rows
c.tabs.position = "top"
c.tabs.show = "multiple"       # hide the bar entirely when only 1 tab
c.tabs.padding = {"top": 6, "bottom": 6, "left": 10, "right": 10}
c.tabs.indicator.width = 2
c.tabs.title.format = "{index}: {current_title}"
c.tabs.favicons.scale = 0.9

# ---- Downloads panel ----
c.colors.downloads.bar.bg = BG
c.colors.downloads.start.fg = BLACK
c.colors.downloads.start.bg = CREAM_DIM
c.colors.downloads.stop.fg = BLACK
c.colors.downloads.stop.bg = CREAM
c.colors.downloads.error.fg = BG
c.colors.downloads.error.bg = "#c96a5a"

# ---- Hints (the letters that appear over links) ----
c.colors.hints.fg = BLACK
c.colors.hints.bg = CREAM
c.colors.hints.match.fg = CREAM_DIM

# ---- Keyhint popup ----
c.colors.keyhint.fg = FG
c.colors.keyhint.suffix.fg = CREAM
c.colors.keyhint.bg = BG_ALT

# ---- Context menu ----
c.colors.contextmenu.menu.bg = BG_ALT
c.colors.contextmenu.menu.fg = FG
c.colors.contextmenu.selected.bg = CREAM
c.colors.contextmenu.selected.fg = BLACK
c.colors.contextmenu.disabled.fg = FG_DIM

# ---- Web page dark-mode tuning (so pages read closer to your palette) ----
c.colors.webpage.bg = BG
config.set("colors.webpage.darkmode.policy.images", "never")
config.set("colors.webpage.darkmode.contrast", 0.0)
