-- Curves: no bounce anywhere, just clean fast decel
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeOutExpo",    { type = "bezier", points = { {0.16, 1},    {0.3, 1}     } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("snap",           { type = "bezier", points = { {0.1, 0},     {0, 1}       } })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 6,    bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 2.6,  bezier = "easeOutExpo" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 1.6,  bezier = "snap",         style = "popin 96%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.4,  bezier = "snap",         style = "popin 96%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 2.2,  bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.9,  bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 4.5,  bezier = "snap" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 4.5,  bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4.5,  bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 2,    bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 2.2,  bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.8,  bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 2.4,  bezier = "snap",         style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 1.6,  bezier = "snap",         style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 2.4,  bezier = "snap",         style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 8,    bezier = "easeOutExpo" })
