# vim:ft=kitty
## name: Adwaita darker (muted beige/grey)
## license: MIT
## author: Emil Löfquist (https://github.com/ewal) — recolored
## upstream: https://github.com/ewal/kitty-adwaita/blob/main/adwaita_darker.conf
## blurb: Adwaita darker recolored into a muted beige/grey/gold palette

background                #000000
foreground                #d3cdbe
selection_background      #2a2822
selection_foreground      #c2bcae
url_color                 #b89b6a
wayland_titlebar_color    system
macos_titlebar_color      system
cursor                    #c9beac
cursor_text_color         #1b1a17
active_border_color       #2a2822
inactive_border_color     #201f1c
bell_border_color         #8a7a63
visual_bell_color         none
active_tab_background     #141311
active_tab_foreground     #e8e3d8
inactive_tab_background   #211f1b
inactive_tab_foreground   #a89f8f
tab_bar_background        none
tab_bar_margin_color      none

color0                    #1b1a17
color1                    #8a6e5c
color2                    #8f8770
color3                    #b89b6a
color4                    #a8916b
color5                    #9c8a76
color6                    #a39984
color7                    #d3cdbe
color8                    #6f6a5e
color9                    #a68872
color10                   #ada58c
color11                   #d4b579
color12                   #c7ac83
color13                   #b9a690
color14                   #bdb3a0
color15                   #ede8dc
